### ISSUE TITLE
Stream new rows on console

### ISSUE THREAD

**Issue by schroeca** [OE-FET/JISA#14]
Using the ResultStream works perfectly for streaming large data to a file. It would be great to have an option to stream the data to "System.out" in parallel for debugging.

In my case, I receive new data every 10 to 15 seconds and I would like to have the new row printed on the console using an "easy" method call, like "results.output(newRowsOnly);"

**Comment by schroeca** [comment]
I solved the "issue" by simply adding a rowListener.

**Comment by WuhrlWuhrd** [comment]
All's well that ends well, as they say. 😉

________________________________
